name: action-executor

replicaCount: 1

image:
  tag: latest
  repository: 339713081046.dkr.ecr.us-east-1.amazonaws.com/action
  imagePullPolicy: Always

readinessProbe:
  enabled: false

livenessProbe:
  enabled: true
  # For the liveness probe we'll wait a full 2 minutes, just incase this service takes a while to start-up
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 9
  successThreshold: 1
  failureThreshold: 3

  probeType: httpGet

  scheme: HTTP
  path: /healthz
  port: default-service

service:
  enabled: true
  annotations: {}
  type: ClusterIP
  port: 8000
  targetPort: 8000
  name: default-service
  # allocateLoadBalancerNodePorts: false
  # externalTrafficPolicy: Local
  additionalPorts: []

rbac:
  create: true
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]
  clusterWideAccess: true
